import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import HeaderComponent from "@/components/Header";
import FooterComponent from "@/components/FooterComponent";
import SubHeader from "@/components/SubHeader";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";

import { AppSidebar } from "@/components/app-sidebar";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SidebarProvider>
          <AppSidebar />
          <main
            className={`${geistSans.variable} ${geistMono.variable} antialiased ${roboto.className}  w-screen`}
          >
            {" "}
            <HeaderComponent></HeaderComponent>
            <SubHeader></SubHeader>
            {children}
            <FooterComponent></FooterComponent>
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
